name: vulnerable-secret

on:
  ##pull_request:
    ##types: opened
  workflow_dispatch:
    inputs:
      title:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      password: ${{ secrets.password }}
    steps:
      - name: echo PR title
        ##run: echo ${{ github.event.pull_request.title }}
        run: echo ${{ inputs.title }}